//@flow
export type ScheduleModel = {
    yc_id: number,
    ma_yeucau: string,
    trangthai_ten: string,
    CN_ID: number,
    PGD_ID: number,
    cusid: number,
    MaThueBao: string,
    ho_ten: string,
    dien_thoai: string,
    dia_chi: string,
    do_uutien_ten: string,
    ten_loai_yeucau: string,
    ten_dichvu: string,
    nhom: string,
    ngay_hen: string,
    noi_dung: string,
    ma_trangthai: string,
    subStatus: string,
    // yc_id: number,
    // CN_ID: number,
    // PGD_ID: number,

    // ma_yeucau: string,
    // trangthai_ten: string,

    // cusid: number,
    // ho_ten: string,
    // dien_thoai: string,
    // dia_chi: string,

    // do_uutien_ten: string,
    // ten_loai_yeucau: string,
    // ten_dichvu: string,

    // ngay_hen: string,
    // noi_dung: string,
    // ma_trangthai: string,
    // subStatus: string
    // do_uutien: number,
    // trang_thai: string,
    // ngay_tao: Date,
    
    // ngay_xuly: Date,
    // nd_tao_id: number,
    // nd_theolich_id: number,
    // nd_xuly_id: number,
    // ghi_chu: string,
    // ma_loai_yeucau: string,
    // ma_ketluan_xuly: string,
    // mota_xuly: string,

    // dia_chi_khong_dau: string,
    
    // ho_ten_khong_dau: string,
    // ghichu_nhanvien: string,
    // noidung_danhgia: string,
    // ma_dichvu: string,
    // ghichu_dichvu: string,
    // id_daily: number,
    // id_danhgia: number,
    // doituong_sudung: number,
    // co_taolich: number,
    // nhom: string,
    // thoidiem_xuly: Date,
    // nd_capnhat_id: number,
    // ngay_capnhat: Date,
    // ma_lydo: string,
    
    
    // ten_ketluan_xuly: string,
    // ten_danhgia: string,
    
    // ten_daily: string,
    // ten_chinhanh: string,
    // TenPGD: string,
    // nd_TiepNhan: string,
    // nd_TheoLich: string,
    // nd_XuLy: string,
    // dtNVTL: string,
    // nd_theolich_dienthoai: string,
    // nd_capnhat: string,
    // lydo_huy: string,
    // ThoiGianDaQua: string,
    // ma_nguyennhan: string,
    // ChiNhanh: string,
    // NguoiDung: string,
    // ngay_hen_text: string,
    
    co_nguyennhan_hoantat: number
}